### ISSUE TITLE
Expected object to always be accessible by owner

### ISSUE THREAD

**Issue by toddself** [digitalsadhu/admittance#18]
From the documentation on expressions I would expect the following to work:

```
var check = admittance({}, {1: 'edit'})
check(2).can('edit', 2)
```

Since that second expression validates as `2 === 2`.  (Passing in `2 === 2` also fails).

Regardless of the group to which a member belongs, they should be admitted to content to which they're the owner it feels.

**Comment by digitalsadhu** [comment]
Oh man, I just realised I saw this and then it slipped through my inbox. Sorry about the month late reply! Is this because the permissions object is empty? I'll add a failing test.

**Comment by digitalsadhu** [comment]
Ah ok I see. Admittance doesn't know anything about user with id 2 so currently won't pass an expression check. I think this needs to be the way it behaves as I don't think I can allow an expression check be enough to pass the check function without some kind of permission assignment being present. Perhaps I need to update the documentation to reflect this?
